### ISSUE TITLE
using MRT and mui/material <TextField in a component make <TextField typing slow and lag.

### ISSUE THREAD

**Issue by SaberRajabi1990** [KevinVandy/material-react-table#1201]
### material-react-table version

2.13.0

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

Please help. Just open sandbox and type fast and BackSpace in <TextField . when I remove <FullMaterialTable that using MRT  <TextField working fine.

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/p/sandbox/materialreacttableandformik-vy4l5f

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
welp, this is definitely not a minimal repro. Way too much code to dig through.

There is "intentional lag" for the search box implied internally. We call it debouncing, and not lag though. It is supposed to be a good thing. MRT waits 400ms until the user has stopped typing to apply the new global filter.
