### ISSUE TITLE
Table rows disappear when toggling full screen

### ISSUE THREAD

**Issue by evitalv** [KevinVandy/material-react-table#259]
### material-react-table version

v1.4.3

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

When using infinite scrolling, toggle the table to full screen and then toggle back. Only the first five rows will be displayed.

### Minimal, Reproducible Example - (Optional, but Recommended)

This is reproducible on the official site:
https://www.material-react-table.com/docs/examples/infinite-scrolling

### Do you intend to try to help solve this bug with your own PR?

No, because I don't know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This seems to be a bug with TanStack Virtual measuring the table body at the wrong time. I'll have to look into this. Good thing it only happens when `enableRowVirtualization` is true

**Comment by evitalv** [comment]
This doesn't really work for me. When I set overscan to 10, I see 11 rows when exiting full screen, but when I scroll lower (below the first 11 rows) there's just emptiness. If I set overscan to 20 I get 21 rows and then nothing.

**Comment by KevinVandy** [comment]
> This doesn't really work for me. When I set overscan to 10, I see 11 rows when exiting full screen, but when I scroll lower (below the first 11 rows) there's just emptiness. If I set overscan to 20 I get 21 rows and then nothing.

Hmm in my experience, after scrolling a bit more, it loads all the new rows

**Comment by duckboy81** [comment]
Troubleshooting this right now. It appears the bad combo is `enableRowVirtualization` and `enableBottomToolbar`. Disabling either one of these will prevent the issue.

Digging into it, `MRT_BottomToolbar` seems to be the culprit. If you pass your own `renderBottomToolbar`, `MRT_BottomToolbar` is not used and there is no issue. 

Removing the following `ref` prop from the `Toolbar` component in `MRT_BottomToolbar` seems to prevent the issue, but I'm doing some more research now.

https://github.com/KevinVandy/material-react-table/blob/aa72893599d091fd0a77f7d1732219f36e13e33d/packages/material-react-table/src/toolbar/MRT_BottomToolbar.tsx#L45-L51

Interestingly, manually attaching my own `MutationObserver` to the "table body section" (I've since forgot what it's actually called) would show that the "table body section" is removed from DOM and the observer loses any new updates when the bug is occurring. When things work normally, the `MutationObserver` is unaffected and new updates are passed correctly.

The final update the `MutationObserver` sees when exiting fullscreen is a `0px` "table body section" height so all rows are removed except for the number of rows specified in the `overscan` setting.
