### ISSUE TITLE
Performance issues when editing

### ISSUE THREAD

**Issue by scott-avery** [KevinVandy/material-react-table#39]
### material-react-table version

0.34.1

### Describe the bug and the steps to reproduce it

see the sandbox, the library has severe performance problem for large scale editable dataset with most table features enabled

### Your Minimal, Reproducible Example - Sandbox (Recommended) or code snippets

https://codesandbox.io/s/material-react-table-performance-testing-spd542?file=/src/TS.tsx

### Do you intend to try to help solve this bug with your own PR?

Maybe, I'll investigate and start debugging

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Not sure what to do with this issue. I don't notice much performance issues with even this example, but I'm also on an M1 MacBook Pro, which seems to run all the row virtualization much better than Windows and Linux.

In general, best not to use multiple features that degrade performance together. If there are dozens of columns, maybe don't allow hundreds of rows to render, and use smaller pagination.

Things that will be worked on in the future include better virtualization, so hopefully that will be better. 

If editing performance seems bad, consider using `onBlur` instead of `onChange` to save new Data
