### ISSUE TITLE
Different UI for tooltips

### ISSUE THREAD

**Issue by fredericbahr** [KevinVandy/material-react-table#501]
### material-react-table version

1.11.0

### react & react-dom versions

18.2

### Describe the bug and the steps to reproduce it

First of all great library.

I noticed that the table uses different tooltips. E.g. the header uses the `title` prop resulting in basic tooltips while the toolbar actions and the header actions use the mui tooltip which results in a different UI/rendering.

I would appreciate a fix that renders all tooltips in the same way. ( I already got it working for mui tooltips)

As both appearances are viable and from my point of view needed for different applications i would like to give the end-user the possibility to decide which tooltip type is used.

Therefore i would introduce a `tooltipType`-prop which can be either `mui` or `basic`. I would be happy to provide a MR if you consent to this change

### Minimal, Reproducible Example - (Optional, but Recommended)

- https://github.com/KevinVandy/material-react-table/blob/main/packages/material-react-table/src/head/MRT_TableHeadCell.tsx#L225
- https://github.com/KevinVandy/material-react-table/blob/main/packages/material-react-table/src/head/MRT_TableHeadCellFilterLabel.tsx#L65

### Do you intend to try to help solve this bug with your own PR?

Yes, I think I know how to fix it and will discuss it in the comments of this issue

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
For the most part, all tooltips are the same. any html titles in the headers are just for accessibility in case they are cutoff with an ellipsis.

**Comment by fredericbahr** [comment]
As the tooltips are shown all the time on hover, not only if the text is cutoff, i would like to make them more consistent within the product.

The basic browser tooltips are used for inputs (e.g. filter), headers, pagination actions.
Icon Button actions provided by you use the mui tooltip

Considering the pagination actions in contrast to other icon buttons of the UI (e.g the drag handle) behaves differently differnt tooltips are used.

I would be happy to provide a MR that unifies this into one style of tooltips to keep the UI consistence

**Comment by KevinVandy** [comment]
Happy to consider it, but the pagination tooltips are built-into the MUI TablePagination component used, so hard to override those and add a MUI tooltip there. 

And again for the headers, I didn't see a point to adding MUI tooltips for those. Just wanted to make accessibility happy with the html tooltip. 

Adding MUI tooltips to the filters will probably act weird for the filterModes feature, because there would be multiple nested MUI tooltips then. The html title for those are again, just for accessibility reasons for when the ellipsis cuts the text off.

IconButtons throughout the table are the only components that get MUI Tooltips, and I think it is good how it is set up.

I'm still happy to have this discussion, but will want to avoid any new prop for this. This is the kind of thing that should just be solved correctly for everyone and not need to be configured, I think.

**Comment by Incin** [comment]
I'm in a similar situation here, at the least is there a clean way to disable the tooltips for the column header for example to then utilize our own?

**Comment by MohammadElokour** [comment]
@fredericbahr  thanks for bring up this issue

In my case I want to show the user a custom tooltip per column header but now they are both rendering:
![image](https://github.com/KevinVandy/material-react-table/assets/48622340/7415ec41-7d4c-4cfa-8ca4-c60ff338d0ba)

Currently my workaround is to set the `header` property in the `MRT_ColumnDef` to an empty string for it to not render the tooltip; this approach is not ideal for the following reasons: 

- I would like to use the value: `column.columnDef.header` so now I will need to replace it with a value in the column meta for example `column.columnDef.meta.label`  to add and access the same value.
- because I didn't need the header property anymore I thought of just removing it but I can't since its required in the type definition and adding it as an empty string doesn't look right to me.

![image](https://github.com/KevinVandy/material-react-table/assets/48622340/9790cf80-0c47-442a-b2fe-688affa98e85)

My approach would be simple, just add a way to disable the default tooltip since its not just the appearance that might need customizing it could also be the value and this can easily be done in the `MRT_ColumnDef` `Header` prop for a custom JSX component.

@KevinVandy your input would be much appreciated

**Comment by KevinVandy** [comment]
Coming back to this, a lot of this has actually been addressed in MRT v2. The headers are the only place where html titles get rendered. Every else like pagination using MUI tooltips. The only remaining improvement here I think would be an easier way to disable the html tooltips. Maybe we disable them for any custom `Header` renders even.

**Comment by MichaelDimmitt** [comment]
What currently exists:
https://github.com/KevinVandy/material-react-table/blob/v2/packages/material-react-table/src/components/head/MRT_TableHeadCell.tsx#L257
```javascript
<Box>
    <Box
      className="Mui-TableHeadCell-Content-Wrapper"
      ... more stuff
    >
       {HeaderElement}
    </Box>
      {column.getCanFilter() && (
          <MRT_TableHeadCellFilterLabel header={header} table={table} />
      )}
      {column.getCanSort() && (
          <MRT_TableHeadCellSortLabel header={header} table={table} />
      )}
</Box>
```

What if you could define labels in the column def along with the header?
It would look like this:
```javascript
<Box>
    <Box
      className="Mui-TableHeadCell-Content-Wrapper"
      ... more stuff
    >
      {HeaderElement}
    </Box>
    {HeaderFilterLabel}
    {HeaderFilterLabel == undefined && column.getCanFilter() && (
        <MRT_TableHeadCellFilterLabel header={header} table={table} />
    )}
    {HeaderSortLabel}
    {HeaderSortLabel == undefined && column.getCanSort() && (
         <MRT_TableHeadCellSortLabel header={header} table={table} />
    )}
</Box>

```

(This would require an update to the docs in https://www.material-react-table.com/docs/api/column-instance-apis
and possibly some other places. Basically wherever Header in columnDef is described this would be added also.)

I think this could solve all issues posed in this issue.
I think the only current way to do this right now is to re-write the entire table just to fix the label.

Started using the library recently! 

Happy to be part of the discussion and hopefully this is helpful. 
Id be happy to put up a pr.

**Comment by MichaelDimmitt** [comment]
My case for why adding {HeaderSortLabel} and {HeaderFilterLabel} could be a better solution.
> disable the tooltip for any custom Header

Disabling the tooltip for custom headers would work too; 
However, what if you want to only change just the sort label? (which is why I am here 😅)

Then you would need to write both the new sort label and a new filter label.
If you were happy with the current filter label you would copy it from this library.

But you would need to check back periodically to keep it up to date if that filter label that you were happy with ever changed.

another benefit to having both {HeaderSortLabel} and {HeaderFilterLabel} added is that you build the tooltip and you would see it work and then when the filter label did not update you would see that you are missing a key.

Whereas if you defined it yourself you might forget to put in the filter label logic and only add the sort label.

**Comment by KevinVandy** [comment]
Now that the Html title attributes have all been removed as of v2.11, I'm closing this

**Comment by KevinVandy** [comment]
@MichaelDimmitt Interesting ideas. Though if you really need to, you can override the entire TableCell children in `muiTableHeadCellProps.children`, and you can import any of the existing MRT components to render in that override. So there is still a backdoor option that exists currently. You could copy and paste the source code innards and modify from there.
