### ISSUE TITLE
Unable to manage customFilterFns manually

### ISSUE THREAD

**Issue by tdanh2k** [KevinVandy/material-react-table#54]
### material-react-table version

v0.40.10

### Describe the bug and the steps to reproduce it

1. Create table with these props: manualFiltering, enableColumnFilters, enableColumnFilterModes, onFilterFnsChange.
2. Manage the customFilterFns state.
3. After that, the filter modes were unable to be switched despite changes being visible when capture by useEffect

### Your Minimal, Reproducible Example - Sandbox (Recommended) or code snippets

https://codesandbox.io/s/material-react-table-check-jpysue?file=/src/App.js

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Thank you for the clear reproducible issue.

I believe the root issue has been fixed in `0.40.11`, though, be advised that you would need to initialize the columnFilterFns state something like this with the default filterFns you want each column to use if you manage that state yourself. Otherwise they will all be undefined.

https://codesandbox.io/s/material-react-table-check-forked-mismkc?file=/src/App.js

A possibly better alternative to managing the state yourself, would be to simply read it from `tableInstanceRef.current?.getState()?.columnFilterFns` if you follow [this guide](https://www.material-react-table.com/docs/guides/table-state-management#access-the-underlying-table-instance-reference)

**Comment by KevinVandy** [comment]
[8118164](https://github.com/KevinVandy/material-react-table/commit/8118164cc33fa5d3c6f2e1bde94cd9fcd86f5bc0)

**Comment by tdanh2k** [comment]
Thank you for your quick and timely response! You've saved me hours or searching for an answer!
