### ISSUE TITLE
Not able to exit from edit mode while using cell edit

### ISSUE THREAD

**Issue by VeenaGangal** [KevinVandy/material-react-table#617]
### material-react-table version

v1.14.0

### react & react-dom versions

>18

### Describe the bug and the steps to reproduce it

I am using Select from MUI for multi select dropdown as custom edit component for one of the columns in material-react-table. Can we use any prop in column definition to come out of exit mode when clicking outside the cell?

`Edit: ({ cell, column, table }) => {       
        return (
          <FormControl>
            <Select 
              labelId="demo-multiple-checkbox-label"
              id="demo-multiple-checkbox"
              multiple                         
              value={cell.getValue<string>().split(",")}             
              onChange={(event) =>
                handleSaveCell(cell, event.target.value.toString())
              }             
              renderValue={(selected) => selected.join(", ")}             
            >
              {names.map((name, index) => (
                <MenuItem key={index} value={name}>                  
                  <Checkbox
                    key={index}
                    defaultChecked={
                      cell.getValue<string>().split(",").indexOf(name) > -1
                    }                   
                  />
                  <ListItemText primary={name} />
                </MenuItem>
              ))}
            </Select>
          </FormControl>
        );
      }`

### Minimal, Reproducible Example - (Optional, but Recommended)

Passing Edit in column definition for custom edit component.

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
need to make this more clear in the docs. It's just

table.setEditingCell(null);

**Comment by VeenaGangal** [comment]
@KevinVandy - Not clear about your suggestion. Where to use table.setEditingCell(null) ?

**Comment by githorse** [comment]
@VeenaGangal I'm not sure how to do it from the `Edit` component, but you could probably do this by 1) creating and passing in a [table ref](https://www.material-react-table.com/docs/api/table-instance-apis#table-instance-apis), so that you have a `table` available outside the MRT component; 2) wrapping your component in a [MUI click-away listener](https://mui.com/material-ui/react-click-away-listener/), and 3) calling the `table.setEditingCell(null)` from the click-away listener `onClickAway` event. (Haven't tried this myself so not sure about the details.)
